### ISSUE TITLE
ltspice does not read exports from LTspice AC

### ISSUE THREAD

**Issue by JacobEFO** [JacobEFO/ltspice#1]
Error code:

Traceback (most recent call last):
  File "demo.py", line 18, in <module>
    freq, mag, deg = ltspice.ltspiceReadAC(fname)
  File "/Users/JEO/Google_Drive/Python/LTspice/ltspice.py", line 28, in ltspiceReadAC
    for line in f:
  File "/Users/JEO/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 70: invalid start byte

**Comment by JacobEFO** [comment]
This is officially fixed. 

Encoding changed to 'cp1252'
